server:
  port: 2222

spring:
  application:
    name: gateway-service

zuul:
  sensitive-headers:
    - Cookie
    - Set-Cookie
  routes:
    registration-key:
      path: /registration-key/**
      serviceId: user-service
      stripPrefix: false
    login:
      path: /login/**
      serviceId: user-service
      stripPrefix: false
    users:
      path: /users/**
      serviceId: user-service
      stripPrefix: false
    offices:
      path: /offices/**
      serviceId: user-service
      stripPrefix: false
    cars:
      path: /cars/**
      serviceId: user-service
      stripPrefix: false
    contact-info:
      path: /contact-info/**
      serviceId: user-service
      stripPrefix: false
    roles:
      path: /roles/**
      serviceId: user-service
      stripPrefix: false
    contact-types:
      path: /contact-types/**
      serviceId: user-service
      stripPrefix: false
    location:
      path: /location/**
      serviceId: maps-service
      stripPrefix: false
    route:
      path: /route/**
      serviceId: maps-service
      stripPrefix: false
    matches:
      path: /matches/**
      serviceId: matching-service
      stripPrefix: false
    likes:
      path: /likes/**
      serviceId: matching-service
      stripPrefix: false
    dislikes:
      path: /dislikes/**
      serviceId: matching-service
      stripPrefix: false

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
      
matching-service:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: http://localhost:4444
    ConnectTimeout: 1000
    ReadTimeout: 3000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100
maps-service:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: http://localhost:3333
    ConnectTimeout: 1000
    ReadTimeout: 30000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100
# for localhost, handling time out issues
user-service:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: http://localhost:5555
    ConnectTimeout: 1000
    ReadTimeout: 30000    # Increased time out to handle requests that may take too long
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100
