server:
  port: 2222

spring:
  application:
    name: gateway-service

zuul:
  routes:
    registration-key:
      path: /registration-key/**
      serviceId: user-service
      stripPrefix: false
    login:
      path: /login/**
      serviceId: user-service
      stripPrefix: false
    users:
      path: /users/**
      serviceId: user-service
      stripPrefix: false
    offices:
      path: /offices/**
      serviceId: user-service
      stripPrefix: false
    cars:
      path: /cars/**
      serviceId: user-service
      stripPrefix: false
    contact-info:
      path: /contact-info/**
      serviceId: user-service
      stripPrefix: false
    roles:
      path: /roles/**
      serviceId: user-service
      stripPrefix: false
    contact-types:
      path: /contact-types/**
      serviceId: user-service
      stripPrefix: false
    location:
      path: /location/**
      serviceId: maps-service
      stripPrefix: false
    route:
      path: /route/**
      serviceId: maps-service
      stripPrefix: false
    matches:
      path: /matches/**
      serviceId: matching-service
      stripPrefix: false
    likes:
      path: /likes/**
      serviceId: matching-service
      stripPrefix: false
    dislikes:
      path: /dislikes/**
      serviceId: matching-service
      stripPrefix: false

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka